"""Added created at in LotsOfData

Revision ID: 98287ae9ff1f
Revises: af093effc33c
Create Date: 2025-08-07 22:37:49.518634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98287ae9ff1f'
down_revision: Union[str, Sequence[str], None] = 'af093effc33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotsofdataforpagination', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotsofdataforpagination', 'created_at')
    # ### end Alembic commands ###
