"""Added Lots of Data table to store huge amount of records

Revision ID: af093effc33c
Revises: d8cfbb9245d1
Create Date: 2025-08-07 07:54:02.844497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af093effc33c'
down_revision: Union[str, Sequence[str], None] = 'd8cfbb9245d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotsofdataforpagination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotsofdataforpagination')
    # ### end Alembic commands ###
